app = "flow-sweepstakes"
primary_region = "sea"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 4000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024

[[http_service.checks]]
grace_period = 10
interval = "30s"
method = "GET"
timeout = "5  path =/api/sweepstakes
