
# fly.toml app configuration file generated for flow-sweepstakes on 2025-07-17T00:40:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flow-sweepstakes"
primary_region = "sea"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 4000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024

[[http_service.checks]]
grace_period = 10
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/sweepstakes"

