# fly.toml app configuration file for flow-sweepstakes-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app =flow-sweepstakes-backendprimary_region = "iad"

[build]
  dockerfile = Dockerfile"env]
  PORT = "8080

[http_service]
  internal_port = 8080force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 processes = ["app]

[[http_service.checks]]
  grace_period = 10
  interval = 30s"
  method =GET"
  timeout = "5  path =/api/sweepstakes
[machine]
  cpu_kind = shared"
  cpus = 1
  memory_mb = 256 